use crate::maker::level::LevelTag;

#[derive(Clone, Debug)]
pub enum UiAction {
    StartGame,
    CloseOverlay,
    Resume,
    QuitToTitle,
    QuitApp,
    // Maker pause menu
    MakerRetry,
    MakerCloseSignDialog,
    // Local level browser
    BrowseOpen,
    BrowsePlay(String),
    BrowseEdit(String),
    BrowseDelete(String),
    BrowseConfirmDelete(String),
    BrowseCancelDelete,
    BrowseSelect(String),
    BrowseClearSelection,
    BrowseToggleTag(LevelTag),
    BrowseToggleVerified,
    BrowseSetDifficulty(Option<u8>),
    BrowseCycleSort,
    BrowseSetQuery(String),
    BrowseClearQuery,
    SetKeyboardCaptured(bool),
    // Maker toolbar / HUD
    OpenPartPicker,
    MakerSetBrushTab(u8),
    MakerSelectBlock(u8),
    MakerSelectEntity(u8),
    MakerCycleShape,
    MakerRotateBrushBlock,
    MakerToggleWaterlog,
    MakerRotateBrush,
    MakerCycleLinkChannel,
    MakerUndo,
    MakerRedo,
    MakerSave,
    MakerOpenLoadPanel,
    MakerLoadSlot(String),
    MakerToggleMode,
    // Entity / track inspector
    MakerInspParamDelta(f32),
    MakerInspCycleContents,
    MakerInspContentsDelta(i32),
    MakerInspYawDelta(f32),
    MakerInspLinkDelta(i32),
    MakerInspTrackCycle,
    MakerInspTrackModeToggle,
    MakerInspTrackSpeedDelta(f32),
    MakerInspTrackReverse,
    MakerInspDeleteEntity,
    MakerInspTrackDelete,
    MakerInspEditSignText,
    MakerInspSetSignText(String),
    MakerInspCancelSignText,
}
