use std::sync::{Arc, Mutex};

use crate::app::SharedUi;
use crate::maker::level::LevelTag;

#[derive(Clone, Debug)]
pub enum UiAction {
    StartGame,
    OpenSettings,
    OpenCredits,
    OpenLevelSelect,
    PlayBundledLevel(u8),
    MakerRemix,
    CloseOverlay,
    Resume,
    QuitToTitle,
    QuitApp,
    SetMasterVol(f32),
    SetSfxVol(f32),
    SetMusicVol(f32),
    SaveSettings,
    NextLanguage,
    SetLanguage(String),
    // Maker toolbar
    MakerToggleMode,
    MakerSelectBlock(u8),
    MakerToggleBrushTab,
    /// Direct tab: 0=Blocks, 1=Entities, 2=Tracks
    MakerSetBrushTab(u8),
    /// Open the fullscreen four-category part picker.
    OpenPartPicker,
    MakerSelectEntity(u8),
    MakerRotateBrush,
    MakerRotateBrushBlock,
    MakerCycleShape,
    MakerToggleWaterlog,
    MakerCycleLinkChannel,
    MakerUndo,
    MakerRedo,
    MakerSave,
    MakerLoad,
    MakerNewLevel,
    MakerOpenLoadPanel,
    MakerLoadSlot(String),
    MakerSaveAs(String),
    MakerDismissClear,
    MakerRetry,
    MakerPublish,
    MakerExportCode,
    MakerImportCode(String),
    MakerCopyCode,
    MakerInspParamDelta(f32),
    MakerInspYawDelta(f32),
    MakerInspLinkDelta(i32),
    MakerInspCycleContents,
    MakerInspContentsDelta(i32),
    MakerInspTrackCycle,
    MakerInspDeleteEntity,
    MakerInspTrackModeToggle,
    MakerInspTrackSpeedDelta(f32),
    MakerInspTrackReverse,
    MakerInspTrackDelete,
    MakerInspEditSignText,
    MakerInspSetSignText(String),
    MakerInspCancelSignText,
    MakerCloseSignDialog,
    BrowseOpen,
    BrowsePlay(String),
    BrowseEdit(String),
    BrowseDelete(String),
    BrowseConfirmDelete(String),
    BrowseCancelDelete,
    BrowseSelect(String),
    BrowseClearSelection,
    BrowseToggleTag(LevelTag),
    BrowseToggleVerified,
    BrowseSetDifficulty(Option<u8>),
    BrowseCycleSort,
    BrowseSetQuery(String),
    BrowseClearQuery,
    BrowseAddToCollection,
    OnlineOpen,
    OnlineRefresh,
    OnlinePlay(u64),
    OnlineLike(u64),
    OnlineReport(u64),
    OnlineDelete(u64),
    OnlineDeleteCancel,
    OnlineUpload,
    OnlineSelect(u64),
    OnlineClearSelection,
    /// Request a background download of level data purely to generate a card preview.
    OnlinePreview(u64),
    OnlineSetShelf(u8),
    OnlineSetIdQuery(String),
    OnlineSearchId,
    OnlineSetToken(String),
    /// Import an anonymous creator recovery key (pasted code).
    CreatorImport(String),
    /// Copy the current recovery key to the clipboard.
    CreatorCopyKey,
    OnlineSetQuery(String),
    OnlineSearch,
    OnlineClearQuery,
    OnlineCycleSort,
    LevelInfoOpen,
    LevelInfoFocus(u8),
    LevelInfoCycleClearCondition,
    LevelInfoTimeLimitDelta(i32),
    LevelInfoToggleTag(LevelTag),
    LevelInfoSave,
    LevelInfoClose,
    /// Apply one of the named boundary presets (floor / walls / ceiling).
    LevelInfoPreset(crate::maker::level::BoundaryPreset),
    /// Adjust the global water plane by `delta` cells (applies immediately).
    LevelInfoWaterDelta(i32),
    /// Grow/shrink the play-size half-extents by `delta` on every axis.
    LevelInfoSizeDelta(i32),
    /// Revert the play-size back to auto (derived from content).
    LevelInfoSizeAuto,
    /// Raise/lower the boundary wall height by `delta` cells.
    LevelInfoHeightDelta(i32),
    /// Revert the boundary wall height to auto (from level size).
    LevelInfoHeightAuto,
    SetPointerOverUi(bool),
    SetKeyboardCaptured(bool),
}

#[derive(bevy::prelude::Resource, Clone)]
pub struct UiBridge {
    pub shared: Arc<Mutex<SharedUi>>,
    pub actions: Arc<Mutex<Vec<UiAction>>>,
}
