use crate::maker::level::{BoundaryPreset, LevelTag};

#[derive(Clone, Debug)]
pub enum UiAction {
    StartGame,
    CloseOverlay,
    Resume,
    QuitToTitle,
    QuitApp,
    OpenSettings,
    OpenCredits,
    SetMasterVol(f32),
    SetSfxVol(f32),
    SetMusicVol(f32),
    SaveSettings,
    NextLanguage,
    SetLanguage(String),
    // Maker pause menu
    MakerRetry,
    MakerCloseSignDialog,
    MakerPublish,
    MakerExportCode,
    MakerImportCode(String),
    MakerCopyCode,
    // Level info panel
    LevelInfoOpen,
    LevelInfoCycleClearCondition,
    LevelInfoTimeLimitDelta(i32),
    LevelInfoToggleTag(LevelTag),
    LevelInfoSave,
    LevelInfoClose,
    LevelInfoPreset(BoundaryPreset),
    LevelInfoWaterDelta(i32),
    LevelInfoSizeDelta(i32),
    LevelInfoSizeAuto,
    LevelInfoHeightDelta(i32),
    LevelInfoHeightAuto,
    // 0 = name, 1 = author, 2 = description
    LevelInfoSetText(u8, String),
    // Local level browser
    BrowseOpen,
    BrowsePlay(String),
    BrowseEdit(String),
    BrowseDelete(String),
    BrowseConfirmDelete(String),
    BrowseCancelDelete,
    BrowseSelect(String),
    BrowseClearSelection,
    BrowseToggleTag(LevelTag),
    BrowseToggleVerified,
    BrowseSetDifficulty(Option<u8>),
    BrowseCycleSort,
    BrowseAddToCollection,
    BrowseSetQuery(String),
    BrowseClearQuery,
    SetKeyboardCaptured(bool),
    // Maker toolbar / HUD
    OpenPartPicker,
    MakerSetBrushTab(u8),
    MakerSelectBlock(u8),
    MakerSelectEntity(u8),
    MakerCycleShape,
    MakerRotateBrushBlock,
    MakerToggleWaterlog,
    MakerRotateBrush,
    MakerCycleLinkChannel,
    MakerUndo,
    MakerRedo,
    MakerSave,
    MakerOpenLoadPanel,
    MakerLoadSlot(String),
    MakerToggleMode,
    // Entity / track inspector
    MakerInspParamDelta(f32),
    MakerInspCycleContents,
    MakerInspContentsDelta(i32),
    MakerInspYawDelta(f32),
    MakerInspLinkDelta(i32),
    MakerInspTrackCycle,
    MakerInspTrackModeToggle,
    MakerInspTrackSpeedDelta(f32),
    MakerInspTrackReverse,
    MakerInspDeleteEntity,
    MakerInspTrackDelete,
    MakerInspEditSignText,
    MakerInspSetSignText(String),
    MakerInspCancelSignText,
}
